//! Integration tests for the full generate() pipeline.

mod test_helpers;

#[test]
fn test_generate_header_comment() {
    let source = r#"
schema Greeting {
  message: string
}
"#;
    let output = test_helpers::generate_from_source(source);
    assert!(
        output.starts_with("# Generated by eamlc from test.eaml"),
        "output should start with header comment, got: {}",
        &output[..output.len().min(80)]
    );
}

#[test]
fn test_generate_section_comments() {
    let source = r#"
model Haiku = Model(
  id: "anthropic/claude-3-haiku-20240307",
  provider: "anthropic",
  caps: []
)

schema Greeting {
  message: string
}

prompt Greet(name: string) -> Greeting {
  user: "Hello {name}"
}
"#;
    let output = test_helpers::generate_from_source(source);
    assert!(
        output.contains("# --- Schemas ---"),
        "missing schemas section comment"
    );
    assert!(
        output.contains("# --- Models ---"),
        "missing models section comment"
    );
    assert!(
        output.contains("# --- Prompts and Tools ---"),
        "missing prompts section comment"
    );
}

#[test]
fn test_generate_empty_section_no_comment() {
    // No agents -- should not have agents section comment
    let source = r#"
schema Greeting {
  message: string
}
"#;
    let output = test_helpers::generate_from_source(source);
    assert!(
        !output.contains("# --- Agents ---"),
        "should not emit agents section when no agents"
    );
    assert!(
        !output.contains("# --- Models ---"),
        "should not emit models section when no models"
    );
}

#[test]
fn test_generate_declaration_order() {
    // Verify per CONTEXT.md: imports, lets, schemas, models, prompts/tools, agents
    let source = r#"
model Haiku = Model(
  id: "anthropic/claude-3-haiku-20240307",
  provider: "anthropic",
  caps: []
)

schema Greeting {
  message: string
}

prompt Greet(name: string) -> Greeting {
  user: "Hello {name}"
}
"#;
    let output = test_helpers::generate_from_source(source);
    let schemas_pos = output
        .find("class Greeting")
        .expect("should contain schema");
    let models_pos = output.find("HAIKU_CONFIG").expect("should contain model");
    let prompts_pos = output
        .find("async def greet")
        .expect("should contain prompt");

    assert!(
        schemas_pos < models_pos,
        "schemas should come before models"
    );
    assert!(
        models_pos < prompts_pos,
        "models should come before prompts"
    );
}

#[test]
fn test_generate_import_deduplication() {
    let source = r#"
schema A {
  x: string
}

schema B {
  y: int
}
"#;
    let output = test_helpers::generate_from_source(source);
    // "from pydantic import BaseModel" should appear exactly once
    let count = output.matches("from pydantic import").count();
    assert_eq!(
        count, 1,
        "pydantic import should appear exactly once, got {count}"
    );
}

#[test]
fn test_generate_error_decl_skipped() {
    // This tests that generate() doesn't panic on empty programs
    let source = "";
    let output = test_helpers::generate_from_source(source);
    assert!(
        output.contains("# Generated by eamlc"),
        "should have header even for empty program"
    );
}

#[test]
fn test_generate_topological_sort_schemas() {
    // Person references Address -- Address should come first
    let source = r#"
schema Person {
  name: string
  address: Address
}

schema Address {
  street: string
  city: string
}
"#;
    let output = test_helpers::generate_from_source(source);
    let address_pos = output
        .find("class Address")
        .expect("should contain Address");
    let person_pos = output.find("class Person").expect("should contain Person");
    assert!(
        address_pos < person_pos,
        "Address should be emitted before Person (topological sort)"
    );
}

#[test]
fn test_generate_with_filename() {
    let source = r#"
schema Greeting {
  message: string
}
"#;
    let (parse_output, analysis) = test_helpers::parse_and_analyze(source);
    let output = eaml_codegen::generate(&parse_output, &analysis, source, "my_file.eaml");
    assert!(
        output.contains("# Generated by eamlc from my_file.eaml"),
        "should include custom filename in header"
    );
}
